name: CI
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: status-im/nimbus-common-workflow/.github/workflows/common.yml@main
    with:
      test-command: |
        OS=uname -s | tr [:upper:] [:lower:]
        if [[ '${OS}' == 'linux' ]]; then
          echo '/home/runner/.nimble/bin' >> $GITHUB_PATH
        elif [[ '${OS}' == 'windows' ]]; then
          echo '/c/Users/runneradmin/.nimble/bin' >> $GITHUB_PATH
        else
          echo '~/.nimble/bin' >> $GITHUB_PATH
        fi
        nimble test