name: CI
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    uses: status-im/nimbus-common-workflow/.github/workflows/common.yml@main
    with:
      nim-versions: '["version-2-0", "version-2-2", "devel"]'
      test-command: |
        if [[ '${{ runner.os }}' == 'Linux' ]]; then
          echo '/home/runner/.nimble/bin' >> $GITHUB_PATH
        elif [[ '${{ runner.os }}' == 'Windows' ]]; then
          echo '/c/Users/runneradmin/.nimble/bin' >> $GITHUB_PATH
        else
          echo '~/.nimble/bin' >> $GITHUB_PATH
        fi

        nim --version
        nimble --version
        nimble install -y --depsOnly
        nimble test
        env NIMFLAGS="--mm:refc" nimble test
