name: CI
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: status-im/nimbus-common-workflow/.github/workflows/common.yml@main
    with:
      nim-versions: '["version-2-0", "version-2-2", "devel"]'
      test-command: |
        nim --version
        nimble --version
        nimble install -y --depsOnly
        nimble test
        env NIMFLAGS="--mm:refc" nimble test
