name: CI
on:
  push:
    branches:
      - master
      - new-workflow
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: status-im/nimbus-common-workflow/.github/workflows/common.yml@main
